"""End-to-end Celery tests (requires live KubeMQ broker).

Run with: pytest tests/test_celery_e2e.py -m e2e
Requires: KUBEMQ_BROKER_ADDRESS environment variable or localhost:50000
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.e2e


class TestCeleryE2E:
    def test_basic_task_execution(self): ...
    def test_task_with_countdown(self): ...
    def test_task_with_eta(self): ...
    def test_task_retry(self): ...
    def test_task_chain(self): ...
    def test_task_group(self): ...
    def test_task_chord(self): ...
    def test_celery_inspect_active(self): ...
    def test_celery_control_shutdown(self): ...
    def test_flower_events(self): ...
    def test_priority_routing(self): ...
    def test_result_backend_get(self): ...
    def test_multiple_workers(self): ...
